version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: moneydb
    restart: always
    environment:
      POSTGRES_USER: money
      POSTGRES_PASSWORD: password
      POSTGRES_DB: moneydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
